<?php

// autoload_namespace.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Twig_Extensions_' => $vendorDir . '/slim/extras/Views/Extension/',
    'Twig_' => $vendorDir . '/twig/twig/lib/',
    'Symfony\\Component\\Console' => $vendorDir . '/symfony/console/',
    'Slim' => $vendorDir . '/slim/slim/Slim/',
    'Fuel\\Validation' => $vendorDir . '/fuel/validation/classes/',
    'Doctrine\\ORM' => $vendorDir . '/doctrine/orm/lib/',
    'Doctrine\\DBAL' => $vendorDir . '/doctrine/dbal/lib/',
    'Doctrine\\Common' => $vendorDir . '/doctrine/common/lib/',
);
