<?php

namespace Infrastructure\Persistence\Doctrine\Proxies\__CG__\Domain\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \Domain\Entities\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function getIdentifier()
    {
        $this->__load();
        return parent::getIdentifier();
    }

    public function setIdentifier($identifier)
    {
        $this->__load();
        return parent::setIdentifier($identifier);
    }

    public function getToken()
    {
        $this->__load();
        return parent::getToken();
    }

    public function setToken($token)
    {
        $this->__load();
        return parent::setToken($token);
    }

    public function getTimeout()
    {
        $this->__load();
        return parent::getTimeout();
    }

    public function setTimeout($seconds)
    {
        $this->__load();
        return parent::setTimeout($seconds);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setDate(\DateTime $date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function addPost(\Domain\Entities\Post $post)
    {
        $this->__load();
        return parent::addPost($post);
    }

    public function getPosts()
    {
        $this->__load();
        return parent::getPosts();
    }

    public function refreshTimeout(\DateInterval $interval = NULL)
    {
        $this->__load();
        return parent::refreshTimeout($interval);
    }

    public function refreshIdentifier()
    {
        $this->__load();
        return parent::refreshIdentifier();
    }

    public function refreshToken()
    {
        $this->__load();
        return parent::refreshToken();
    }

    public function refresh()
    {
        $this->__load();
        return parent::refresh();
    }

    public function getTokenString()
    {
        $this->__load();
        return parent::getTokenString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function isNew()
    {
        $this->__load();
        return parent::isNew();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'username', 'password', 'identifier', 'token', 'timeout', 'date', 'id', 'posts');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}