{% macro input(type, model, property, name, label, placeholder) %}

{% set invalid = '' %}

{% if model.getMessageFor(property) %}
    {% set invalid = ' error' %}
    {% set message = model.getMessageFor(property) %}
{% endif %}

{% set id = name ~ "." ~ property %}

<div class="control-group{{ invalid }}">
    <label for="{{ id }}" class="control-label">{{ label }}</label>
    <div class="controls">
        <input type="{{ type }}" placeholder="{{ placeholder|default(property) }}" value="{{ attribute(model, property) }}" class="input-xlarge" id="{{ id }}" name="{{ name }}[{{ property }}]" />
        {% if invalid %}
        <p class="help-block error">
            {{ message }}
        </p>
        {% endif %}
    </div>
</div>
{% endmacro %}