<!doctype html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %} - Super Blorg!</title>
        <link rel="stylesheet" href="/Assets/css/bootstrap.min.css" type="text/css" />
        <link rel="stylesheet" href="/Assets/css/bootstrap-responsive.min.css" type="text/css" />
        <link rel="stylesheet" href="/Assets/css/superblorg.css" type="text/css" />
    </head>
    <body>
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="/">Superblorg</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li>
                                <a href="/users">Authors</a>
                            </li>
                            <li>
                                <a href="/register">Register</a>
                            </li>
                            <li>
                                <a href="/login">Login</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <div class="container">
            <p>
                Super Blorg! &copy; 2020 - Yeah It's The Future
            </p>
        </div>
    </body>
</html>