{% extends "layout.phtml" %}

{% import "macros/controls.phtml" as controls %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="hero-unit">
    <h1>Join Super Blorg!</h1>
    <p>
        The Super Blorg! &reg; community would love to welcome you. Surrender to the loving embrace of Super Blorg &reg;
    </p>
    <p>
        <a href="#" class="btn btn-primary btn-large">Learn More!</a>
    </p>
</div>

<div class="row">
    <div class="span6">
        <p>
            We just need to get a bit of information from you.
        </p>
        <form action="/register" method="post" class="form-horizontal well">

            {{ controls.input('text', user, 'username', 'user', 'Desired username:')  }}
            
            {{ controls.input('password', user, 'password', 'user', 'Password:') }}

            {{ controls.input('password', user, 'passwordConfirm', 'user', 'Confirm password:', 'confirm password') }}

            <div class="form-actions">
                <input type="submit" value="Register!" class="btn btn-primary btn-large" />
            </div>
        </form>
    </div>
    <div class="span6">
        <h2>Reasons To Join Super Blorg &reg;</h2>
        <ul>
            <li>We aren't your grandfather's blogging tool.</li>
            <li>We aren't your grandmother's blogging tool.</li>
            <li>We aren't your dad's blogging tool.</li>
            <li>The cool kids are doing it.</li>
            <li>Our style is completely original.</li>
        </ul>
        <p>
            Not convinced? Read what these satisfied users have to say!
        </p>
        <blockquote>
            <p>
                Super Blorg! &reg; is like the one slice of pizza left with bacon on it!
            </p>
            <small>Jon Smith</small>
        </blockquote>

        <blockquote>
            <p>
                Blorg? Instead of blog? Bold move bro....
            </p>
            <small>Jeremiah Prentice</small>
        </blockquote>
    </div>
</div>
{% endblock %}
